import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import random

st.set_page_config(page_title="AI Water & Power Tracker", layout="wide", page_icon="💧")

st.title("💧⚡ AI Water & Power Tracker")
st.caption("Built from your original Python script")

# ====================== SIDEBAR ======================
st.sidebar.header("⚙️ Settings")

power_unit = st.sidebar.selectbox("Power unit", ["kWh", "MWh"])
water_unit = st.sidebar.selectbox("Water unit", ["Liters", "Gallons"])
power_label = "MWh" if power_unit == "MWh" else "kWh"
water_label = "Gallons" if water_unit == "Gallons" else "Liters"

def conv_power(v): return v / 1000 if power_label == "MWh" else v
def conv_water(v): return v * 0.264172 if water_label == "Gallons" else v

total_water = st.sidebar.number_input(f"Total Water ({water_label})", value=2400.0)
total_power = st.sidebar.number_input(f"Total Power ({power_label})", value=72000.0)
co2_per_kwh = st.sidebar.number_input("CO₂ per kWh (kg)", value=0.4)
electricity_price = st.sidebar.number_input("Electricity price ($)", value=0.12)

cost_limit = st.sidebar.number_input("Total Cost Limit ($)", value=8000.0)
co2_limit = st.sidebar.number_input("Total CO₂ Limit (kg)", value=25000.0)

# ====================== JOBS ======================
st.sidebar.header("Jobs (GPU-hours)")

default_jobs = {
    "Training Job A - Large Language Model": 4.0,
        "Inference Job B - Chatbot Service": 1.5,
            "Training Job C - Image Generation": 3.0,
                "Batch Job D - Data Processing": 1.0,
                    "Fine-tuning Job E - Customer Model": 2.5,
                        "Learning from Prince Job F - Genius Model": 3.5,
                            "Dancing Job G - Gloria Kuslide Model": 4.3,
                                "Attention Job H - Naomi Attentive Model": 2.1,
                                    "Joker Job I - Max Never Serious Model": 1.2,
                                        "Etc Job J - Ran Out Of Model Ideas Model": 4.6
                                        }

                                        data_mode = st.sidebar.radio("Data entry mode", ["Manual", "Automatic"])

                                        jobs = {}
                                        if data_mode == "Manual":
                                            for name, default in default_jobs.items():
                                                    jobs[name] = st.sidebar.number_input(name, value=float(default), step=0.1, key=name)
                                                    else:
                                                        min_hr = st.sidebar.number_input("Min GPU-hours", value=1.0)
                                                            max_hr = st.sidebar.number_input("Max GPU-hours", value=5.0)
                                                                if st.sidebar.button("Generate random values"):
                                                                        for name in default_jobs:
                                                                                    jobs[name] = round(random.uniform(min_hr, max_hr), 2)
                                                                                        else:
                                                                                                jobs = default_jobs.copy()

                                                                                                categories_map = {
                                                                                                    "Training Job A - Large Language Model": "Training",
                                                                                                        "Inference Job B - Chatbot Service": "Inference",
                                                                                                            "Training Job C - Image Generation": "Training",
                                                                                                                "Batch Job D - Data Processing": "Batch",
                                                                                                                    "Fine-tuning Job E - Customer Model": "Fine-tuning",
                                                                                                                        "Learning from Prince Job F - Genius Model": "Training",
                                                                                                                            "Dancing Job G - Gloria Kuslide Model": "Training",
                                                                                                                                "Attention Job H - Naomi Attentive Model": "Inference",
                                                                                                                                    "Joker Job I - Max Never Serious Model": "Batch",
                                                                                                                                        "Etc Job J - Ran Out Of Model Ideas Model": "Misc"
                                                                                                                                        }

                                                                                                                                        # ====================== CALCULATIONS ======================
                                                                                                                                        total_weight = sum(jobs.values()) or 1
                                                                                                                                        total_co2 = total_power * co2_per_kwh
                                                                                                                                        total_cost = total_power * electricity_price

                                                                                                                                        results = []
                                                                                                                                        for i, (name, weight) in enumerate(jobs.items()):
                                                                                                                                            letter = chr(65 + i)
                                                                                                                                                share = weight / total_weight
                                                                                                                                                    water = total_water * share
                                                                                                                                                        power = total_power * share
                                                                                                                                                            co2 = power * co2_per_kwh
                                                                                                                                                                cost = power * electricity_price
                                                                                                                                                                    results.append({
                                                                                                                                                                            "Letter": letter,
                                                                                                                                                                                    "Job": name,
                                                                                                                                                                                            "Category": categories_map.get(name, "Other"),
                                                                                                                                                                                                    "GPU-hours": weight,
                                                                                                                                                                                                            "Share %": share * 100,
                                                                                                                                                                                                                    "Water": water,
                                                                                                                                                                                                                            "Power": power,
                                                                                                                                                                                                                                    "CO2": co2,
                                                                                                                                                                                                                                            "Cost": cost,
                                                                                                                                                                                                                                                    "Power/hr": power / weight if weight else 0,
                                                                                                                                                                                                                                                            "Cost/hr": cost / weight if weight else 0,
                                                                                                                                                                                                                                                                    "CO2/hr": co2 / weight if weight else 0
                                                                                                                                                                                                                                                                        })

                                                                                                                                                                                                                                                                        df = pd.DataFrame(results)
                                                                                                                                                                                                                                                                        df_sorted = df.sort_values("Power", ascending=False).reset_index(drop=True)

                                                                                                                                                                                                                                                                        # ====================== TABS ======================
                                                                                                                                                                                                                                                                        tab1, tab2, tab3, tab4 = st.tabs(["📊 Summary", "📈 Charts & Efficiency", "🔮 What-If Simulator", "📅 Time-Series"])

                                                                                                                                                                                                                                                                        with tab1:
                                                                                                                                                                                                                                                                            st.header("Executive Summary")
                                                                                                                                                                                                                                                                                c1, c2, c3, c4 = st.columns(4)
                                                                                                                                                                                                                                                                                    c1.metric("Total Water", f"{conv_water(total_water):,.1f} {water_label}")
                                                                                                                                                                                                                                                                                        c2.metric("Total Power", f"{conv_power(total_power):,.1f} {power_label}")
                                                                                                                                                                                                                                                                                            c3.metric("Total CO₂", f"{total_co2:,.1f} kg")
                                                                                                                                                                                                                                                                                                c4.metric("Total Cost", f"${total_cost:,.2f}")

                                                                                                                                                                                                                                                                                                    if total_cost > cost_limit:
                                                                                                                                                                                                                                                                                                            st.error(f"⚠️ Total cost exceeds limit (${cost_limit:,.2f})")
                                                                                                                                                                                                                                                                                                                if total_co2 > co2_limit:
                                                                                                                                                                                                                                                                                                                        st.error(f"⚠️ Total CO₂ exceeds limit ({co2_limit:,.1f} kg)")

                                                                                                                                                                                                                                                                                                                            st.subheader("Job Impact Ranking")
                                                                                                                                                                                                                                                                                                                                display_df = df_sorted[["Letter", "Job", "Category", "Share %", "Water", "Power", "CO2", "Cost"]].copy()
                                                                                                                                                                                                                                                                                                                                    display_df["Water"] = display_df["Water"].apply(lambda x: f"{conv_water(x):,.1f}")
                                                                                                                                                                                                                                                                                                                                        display_df["Power"] = display_df["Power"].apply(lambda x: f"{conv_power(x):,.1f}")
                                                                                                                                                                                                                                                                                                                                            display_df["CO2"] = display_df["CO2"].apply(lambda x: f"{x:,.1f}")
                                                                                                                                                                                                                                                                                                                                                display_df["Cost"] = display_df["Cost"].apply(lambda x: f"${x:,.2f}")
                                                                                                                                                                                                                                                                                                                                                    display_df["Share %"] = display_df["Share %"].apply(lambda x: f"{x:.1f}%")
                                                                                                                                                                                                                                                                                                                                                        st.dataframe(display_df, use_container_width=True)

                                                                                                                                                                                                                                                                                                                                                            csv = df_sorted.to_csv(index=False)
                                                                                                                                                                                                                                                                                                                                                                st.download_button("Download Report (CSV)", csv, "job_impact_report.csv")

                                                                                                                                                                                                                                                                                                                                                                with tab2:
                                                                                                                                                                                                                                                                                                                                                                    st.header("Charts & Efficiency")
                                                                                                                                                                                                                                                                                                                                                                        col1, col2 = st.columns(2)
                                                                                                                                                                                                                                                                                                                                                                            with col1:
                                                                                                                                                                                                                                                                                                                                                                                    fig, ax = plt.subplots()
                                                                                                                                                                                                                                                                                                                                                                                            ax.bar(df_sorted["Letter"], [conv_power(p) for p in df_sorted["Power"]], color="orange")
                                                                                                                                                                                                                                                                                                                                                                                                    ax.set_title(f"Power ({power_label})")
                                                                                                                                                                                                                                                                                                                                                                                                            st.pyplot(fig)
                                                                                                                                                                                                                                                                                                                                                                                                                with col2:
                                                                                                                                                                                                                                                                                                                                                                                                                        fig, ax = plt.subplots()
                                                                                                                                                                                                                                                                                                                                                                                                                                ax.bar(df_sorted["Letter"], [conv_water(w) for w in df_sorted["Water"]], color="blue")
                                                                                                                                                                                                                                                                                                                                                                                                                                        ax.set_title(f"Water ({water_label})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                st.pyplot(fig)

                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.subheader("Share of Total Usage")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fig, ax = plt.subplots()
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax.pie(df_sorted["Share %"], labels=df_sorted["Letter"], autopct="%1.1f%%", startangle=90)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.pyplot(fig)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.subheader("Efficiency (lower is better)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eff = df.sort_values("Cost/hr")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.dataframe(eff[["Letter", "Job", "Power/hr", "Cost/hr", "CO2/hr"]], use_container_width=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.success(f"Most efficient: [{eff.iloc[0]['Letter']}] {eff.iloc[0]['Job']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.warning(f"Least efficient: [{eff.iloc[-1]['Letter']}] {eff.iloc[-1]['Job']}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with tab3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.header("What-If Savings Simulator")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            selected = st.multiselect("Select jobs to reduce", df["Letter"].tolist(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          format_func=lambda x: f"[{x}] {df[df.Letter==x]['Job'].values[0]}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if selected:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      same = st.radio("Same % for all?", ["Yes", "No"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              reductions = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if same == "Yes":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pct = st.slider("Reduction %", 0, 100, 20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for letter in selected:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              reductions[letter] = pct / 100
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for letter in selected:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reductions[letter] = st.slider(f"[{letter}] %", 0, 100, 20, key=letter) / 100

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          total_w = total_p = total_c = total_co2s = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rows = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for letter in selected:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      job = df[df.Letter == letter].iloc[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  r = reductions[letter]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              w = job["Water"] * r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          p = job["Power"] * r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      c = job["Cost"] * r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  co2 = job["CO2"] * r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              total_w += w
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          total_p += p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      total_c += c
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total_co2s += co2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rows.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Letter": letter,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Job": job["Job"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Reduction": f"{r*100:.0f}%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Water Saved": round(conv_water(w), 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Power Saved": round(conv_power(p), 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "CO2 Avoided": round(co2, 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Cost Saved": round(c, 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c1, c2, c3, c4 = st.columns(4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c1.metric("Water saved", f"{conv_water(total_w):,.1f} {water_label}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c2.metric("Power saved", f"{conv_power(total_p):,.1f} {power_label}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c3.metric("CO₂ avoided", f"{total_co2s:,.1f} kg")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c4.metric("Cost saved", f"${total_c:,.2f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          st.dataframe(pd.DataFrame(rows), use_container_width=True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          with tab4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              st.header("Time-Series Tracking")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  num_days = st.number_input("Number of days", 1, 30, 7)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ts_mode = st.radio("Mode", ["Manual", "Automatic"], key="ts")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          day_power, day_water = [], []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if ts_mode == "Manual":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for d in range(1, num_days + 1):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c1, c2 = st.columns(2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              with c1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              p = st.number_input(f"Day {d} Power", value=float(conv_power(total_power)), key=f"p{d}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          with c2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          w = st.number_input(f"Day {d} Water", value=float(conv_water(total_water)), key=f"w{d}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      day_power.append(p)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  day_water.append(w)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              min_p = st.number_input("Min power/day", value=float(conv_power(total_power) * 0.8))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      max_p = st.number_input("Max power/day", value=float(conv_power(total_power) * 1.2))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              min_w = st.number_input("Min water/day", value=float(conv_water(total_water) * 0.8))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      max_w = st.number_input("Max water/day", value=float(conv_water(total_water) * 1.2))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if st.button("Generate values"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          day_power = [round(random.uniform(min_p, max_p), 1) for _ in range(num_days)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      day_water = [round(random.uniform(min_w, max_w), 1) for _ in range(num_days)]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if day_power:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  days = list(range(1, len(day_power) + 1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fig, axes = plt.subplots(1, 2, figsize=(12, 4))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  axes[0].plot(days, day_power, marker="o", color="orange")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[0].set_title(f"Power ({power_label})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  axes[1].plot(days, day_water, marker="o", color="blue")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          axes[1].set_title(f"Water ({water_label})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  st.pyplot(fig)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          st.write(f"Average Power: {sum(day_power)/len(day_power):,.1f} {power_label}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  st.write(f"Average Water: {sum(day_water)/len(day_water):,.1f} {water_label}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  streamlit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pandas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  matplotlib